POST http://127.0.0.1:8000/movies
Content-Type: application/json

{
  "title": "title1",
  "year": 1923,
  "director": "director1",
  "description": ""
}

###

GET http://127.0.0.1:8000/movies
Accept: application/json

###

GET http://127.0.0.1:8000/movies/7
Accept: application/json

###

DELETE http://127.0.0.1:8000/movies/8
Accept: application/json

###

GET http://127.0.0.1:8000/actors
Accept: application/json

###
POST http://127.0.0.1:8000/actors
Content-Type: application/json

{
  "name": "Jerzy",
  "surname": "Stuhr"
}

###
GET http://127.0.0.1:8000/actors/7
Accept: application/json

###
DELETE http://127.0.0.1:8000/actors/8
Accept: application/json

###
# currently not working
POST http://127.0.0.1:8000/movies/2/actors
Content-Type: application/json

{
  "actor_id": 2
}